src/ImageFiltering.jl
src/imfilter.jl
test/2d.jl
test/cascade.jl
test/nd.jl

This fixes the bug noted in https://github.com/JuliaImages/ImageFiltering.jl/issues/9#issuecomment-254013441. The inaccuracy noted in the same issue (https://github.com/JuliaImages/ImageFiltering.jl/issues/9#issuecomment-249136104) was presumably fixed in f66e387c0460c18c3010a328e6eab10bba0aaf87, but that fix had a bug that led to the "inadequate" error.
This also introduces `FIRTiled` so it's possible to control explicitly whether the tiled algorithm is used. If nothing else, this is very useful for testing to make sure that all code-paths get exercised.
CC @GunnarFarneback, @tlnagy.

Fix tile sizes and temporary allocation issues in FIR algorithms

---

src/ImageFiltering.jl
src/border.jl
src/imfilter.jl
src/kernelfactors.jl
test/basic.jl

Using the benchmark of #9 (with a switch to `FIRTiled` for the second one), I now get this:
```
BenchmarkTools.Trial: 
samples:          115
evals/sample:     1
time tolerance:   5.00%
memory tolerance: 1.00%
memory estimate:  3.88 mb
allocs estimate:  45
minimum time:     39.40 ms (0.00% GC)
median time:      40.57 ms (0.00% GC)
mean time:        43.80 ms (0.18% GC)
maximum time:     76.27 ms (0.00% GC)
BenchmarkTools.Trial: 
samples:          404
evals/sample:     1
time tolerance:   5.00%
memory tolerance: 1.00%
memory estimate:  3.91 mb
allocs estimate:  533
minimum time:     11.55 ms (0.00% GC)
median time:      11.87 ms (0.00% GC)
mean time:        12.38 ms (0.77% GC)
maximum time:     23.65 ms (2.71% GC)
BenchmarkTools.Trial: 
samples:          356
evals/sample:     1
time …
```

Performance enhancements (fixes #9)

---

src/border.jl
src/mapwindow.jl
test/mapwindow.jl
test/runtests.jl

We've long had several "holes" in Images, of which one is not having a median filter. This PR implements a generic `mapwindow(f, img, window)` for performing linear or nonlinear operations on rectangular "moving windows" of the image. This is an `O(N^d)` algorithm (where `d` is dimensionality and `N` the window size), so it's not efficient for big windows, but it behaves pretty well for small windows.
For example, let's try `median!`:
```julia
julia> img = rand(1000,1000);
julia> @time mapwindow(median!, img, (3,3));
0.179863 seconds (144.01 k allocations: 13.309 MB)
```
which is within 30% of Matlab on my machine (and I suspect Matlab is using multithreading, though I didn't check).
The nice thing about this implementation is that in principle, you can pass *any* function to `mapwindow`: …

Implement a generic `mapwindow` (e.g., medfilt)

---

docs/make.jl

Documenter.jl defaults to the nightly linux build (see https://juliadocs.github.io/Documenter.jl/latest/lib/public.html#Documenter.deploydocs), which is more likely to break than the stable linux build. Fixes #18

explicitly build docs on 0.5

---

test/basic.jl

CC @tkelman (sorry this got forgotten).

Clean up temporary files in tests. Fixes #8.

---

REQUIRE
src/ImageFiltering.jl
src/border.jl
src/imfilter.jl
src/kernel.jl
src/kernelfactors.jl
src/utils.jl
test/runtests.jl
test/triggs.jl

Broken on 0.6 due to https://github.com/JuliaLang/julia/issues/20658, but meanwhile we can fix a bunch of depwarns.

Fix typealias depwarns on 0.6

---

src/border.jl
test/2d.jl
test/nd.jl

While this package exploits non-1 index arrays internally, it turns out I had never tested what happens if you filter an image with non-1 indices. The necessary fixes were gratifyingly modest (just to `padindex`).

Fix padding for inputs with non-1 indices

---

src/imfilter.jl
test/specialty.jl

I recently got a [tip](https://github.com/JuliaLang/julia/pull/23330) on how to compile a 32-bit version of julia on a 64-bit machine. It's long bothered me that the tests here fail on 32-bit, so I took the opportunity to figure out why they are failing and fix the problem.

Fix errors on 32bit platforms

---

docs/make.jl

The function reference for `mapwindow()` is missing, which makes the link [here](https://juliaimages.github.io/ImageFiltering.jl/stable/index.html#Arbitrary-operations-over-sliding-windows-1) broken. I think we just need to tell Documenter to look inside the MapWindow module.

make sure mapwindow() function reference is generated

---

src/kernelfactors.jl

Finally tracked down the source of the longstanding
```julia
WARNING: deprecated syntax "_ as an rvalue around docs/Docs.jl:522".
```

Circumvent a deprecation warning

---

benchmark/benchmarks.jl
benchmark/mapwindow.jl

Useful to judge performance impact of #45. Are there more `mapwindow` cases, that should be benchmarked?

add mapwindow benchmark

---

src/mapwindow.jl
test/mapwindow.jl
test/runtests.jl

See #44. Here is a first implementation. The API is a bit cumbersome and needs to be improved. Currently you have to call 
```julia
mapwindow(f,img,window,border,imginds)
```
Any suggestions for a better API? I would also like to add two convenience functions:
* `strided(inds, stride)` converts a stride into something that can be passed to mapwindow:
```julia
mapwindow(f,...,strided(indices(img), (2,3))) = mapwindow(f,...)[1:2:end,1:3:end]
```
* `mappool(f,img,window)` which does image [pooling](https://discourse.julialang.org/t/image-pooling/5280). This is the special case, where the stride is the size of the window.
```julia
mappool(f,img,window,...) = mapwindow(f,img,...,strided(indices(img), map(length,window))
```

RFC: strided mapwindow

---

src/ImageFiltering.jl
src/kernel.jl
test/gabor.jl
test/runtests.jl

I have added the function gabor in kernel.jl that implements the 2D gabor kernel. I am not clear about how to add tests for checking the function.

Added 2D Gabor filter

---

src/border.jl
test/border.jl

Using the `padarray` function with the `Fill` type on an `OffsetArray` resulted in an error.  This was caused due to an implicit call of `size` on an `OffsetArray` which is an undefined operation. This commit patches the bug JuliaImages/Images.jl/issues/718

Patches `padarray` so that it works on `OffsetArray`

---

.travis.yml
REQUIRE
appveyor.yml
src/ImageFiltering.jl
src/border.jl
src/imfilter.jl
src/kernel.jl
src/kernelfactors.jl
src/mapwindow.jl
src/specialty.jl
src/utils.jl
test/2d.jl
test/basic.jl
test/border.jl
test/cascade.jl
test/gabor.jl
test/gradient.jl
test/mapwindow.jl
test/nd.jl
test/runtests.jl
test/specialty.jl
test/triggs.jl

This incorporates #41 and #64. As I am rushing to leave town for two weeks, most likely without any internet whatsoever, this is quick.
Most of the tests are working on 0.7. You need a fresh build of Julia and you also want https://github.com/JuliaLang/julia/pull/28100 and https://github.com/JuliaLang/julia/pull/28084. While I am gone I would urge members of the Images community to keep trying to get the JuliaImages packages working on 0.7: porting these has shaken out something like a dozen critical bugs in Base Julia and its stdlibs. Having put so much work into Julia and JuliaImages so far, it would be something of a shame if 1.0 got released and we couldn't really run JuliaImages packages.
Discourse advertised a slack channel on Fridays to help people port packages. Good luck!

Latest attempt to get this working on 0.7

---

src/imfilter.jl
test/triggs.jl

This depwarn was caught by the Images.jl tests (but not the tests of this package I think)
```
┌ Warning: `CartesianIndices(inds::Vararg{AbstractUnitRange{Int}, N}) where N` is deprecated, use `CartesianIndices(inds)` instead.
│   caller = _imfilter_inplace_tuple! at imfilter.jl:1270 [inlined]
└ @ Core ~/.julia/dev/ImageFiltering/src/imfilter.jl:1270
```

fix remaining depwarn

---

docs/src/function_reference.md
src/mapwindow.jl
test/mapwindow.jl

Now that Julia has fast keyword arguments, I think we should make use of them to shorten some signatures. This PR is for `mapwindow` and `mapwindow!`. 
I also looked at `imfilter` and `imfilter!`. These would in principle profit from some keyword arguments as well. However
* I personally do not use the more advanced signatures in `imfilter` and `imfilter!`
* There is a lot of "dispatch code" for `imfilter` and `imfilter!` already, which I am not familiar with. While I could blindly add yet another layer, I think it would be much better if a power user of these functions does this properly.
So I prefer not to touch `imfilter` and `imfilter!`, at least for this PR.

mapwindow arguments positional to keywords

---

src/mapwindow.jl

I was going through some old emails and realized none of us had tagged a release containing #75. But then I tested and found the following deprecation warning a bit opaque:
```julia
julia> mapwindow!(identity, out, A, (0:1, 0:1), Inner())
┌ Warning: `mapwindow!(f, out, img, window, border, indices=default_imginds(img, window, border))` is deprecated, use `begin
│     mapwindow!(f, out, img, window, border=border, indices=indices)
│ end` instead.
│   caller = mapwindow!(::Function, ::Array{SArray{Tuple{4},Float64,1,4},2}, ::Array{Float64,2}, ::Tuple{UnitRange{Int64},UnitRange{Int64}}, ::Inner{0}) at deprecated.jl:54
└ @ ImageFiltering.MapWindow ./deprecated.jl:54
```
This PR changes it to
```julia
julia> mapwindow!(identity, out, A, (0:1, 0:1), Inner())
┌ Warning: mapwindow!(f, out, img, …
```

Improve (?) deprecation warning in #75

---

.travis.yml
src/border.jl
src/imfilter.jl
src/kernelfactors.jl
src/utils.jl
test/2d.jl

@zygmuntszpak, does this seem OK?

Provide better support for manually-specified borders (fixes #85)

---

src/ImageFiltering.jl
src/kernel.jl
test/2d.jl
test/mapwindow.jl
test/specialty.jl

The first commit gets the tests passing with the new `IdentityUnitRange` on Julia 1.1. The second is due to my failure to tag https://github.com/JuliaLang/julia/pull/30164 with a backport label.

Fixes for various Julia versions

---

REQUIRE
src/ImageFiltering.jl
test/REQUIRE
test/basic.jl

This provides specializations for `centered`, where the conditional dependency on the relevant packages is handled via Requires.jl.

Handle AxisArray and ImageMeta wrappers with `centered`

---

.gitignore
docs/src/function_reference.md
src/ImageFiltering.jl
src/border.jl
src/borderarray.jl
test/border.jl

add BorderArray

---

Project.toml
src/utils.jl
test/basic.jl

This patch generalizes `centered(A::AbstractArray)` by not assuming indexes of A start at 1.
A side effect of this patch is to corrects the behavior of `imfilter` with accident usage of `centered(::OffsetArray)`
```julia
julia> x = testimage("cameraman")
julia> k = KernelFactors.gaussian(1.5, 11)
OffsetArray(::Array{Float64,1}, -5:5) with eltype Float64 with indices -5:5:
julia> a = imfilter(x, kernelfactors((k, k)))
julia> b = imfilter(x, kernelfactors((centered(k), centered(k))))
julia> a - b
```
```julia
julia> gray.(sum(abs.(a-b)))
0.0
```

correct the behavior of centered for OffsetArray

---

src/kernel.jl
src/kernelfactors.jl
src/specialty.jl

Hello :-)
The DOI Foundation [started recommending a new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). While their URL change may be a bit ironic, it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org) and the old `dx` subdomain is being redirected. So, there is no urgency here.
However, for consistency, this PRs suggests to update all static DOI links accordingly.
Cheers!

Hyperlink DOIs to preferred resolver

---

docs/src/function_reference.md
src/ImageFiltering.jl
src/kernel.jl
test/specialty.jl

In reference to feature request #146. 
Please  let me know if anything isn't done how it should be. I'm keen to learn.

Add Moffat Kernel

---

src/imfilter.jl
test/nd.jl

This fixes filtering of floating-point arrays with `NaN` and large kernels.
According to benchmarks on my machine, the time to check for `NaN`s is up to about 0.5% of the `imfilter` time (for `img::Vector{Float64}` and kernel of length 31).

Don't use FFT when input has NaNs

---

Project.toml
test/border.jl

ColorTypes is used via ImageCore, and so was never explicitly tested for upgradability to v0.10. The old test relied on  `convert(RGB{N0f8}, 0)` throwing an error, but it doesn't anymore.

Fix tests with ColorTypes 0.10

---

src/border.jl
src/imfilter.jl
test/border.jl

Useful for filtering `SVector` or `GeometryTypes.Point` arrays with `NA(x->any(isnan,x))`.
May be also useful to do `NA(ismissing)` in the future, but `imfilter` with `missing`s doesn't work yet for other reasons.
I removed the line `out[nanflag] .= nan(T)`, which may be breaking (changes the behavior of plain `NA()`). I'm not sure why it was there; seems to me like a bug.

Generalize `NA` to take `na` predicate as argument (not just `isnan`)

---

Project.toml
src/mapwindow.jl
test/mapwindow.jl

The deleted assertions fail due to  JuliaArrays/OffsetArrays.jl#104. As a workaround, I tried
```
@assert (imgr .+ kmin)[idx] ⊆ fullimgr
@assert (imgr .+ kmax)[idx] ⊆ fullimgr
```
instead, but that fails due to JuliaLang/julia#35225 when `idx` turns out empty.

Fix mapwindow for offset arrays

---

test/2d.jl
test/runtests.jl

https://github.com/JuliaLang/julia/pull/37085 changed how type parameters
are printed, causing the following error:
```
Borders (issue #85): Test Failed at /home/runner/work/ImageFiltering.jl/ImageFiltering.jl/test/2d.jl:337
Expression: imfilter(A, kern, Fill(0, (3,)))
Expected: ArgumentError("Fill{Int64,1}(0, (3,), (3,)) lacks the proper padding sizes for an array with 2 dimensions")
Thrown: ArgumentError("Fill{Int64, 1}(0, (3,), (3,)) lacks the proper padding sizes for an array with 2 dimensions")
```
See https://github.com/JuliaImages/ImageFiltering.jl/runs/1053929388?check_suite_focus=true#step:5:273 for the CI failure.

Fix tests to be agnostic to type printing

---

.github/workflows/benchmark.yml

In this way, benchmark CI is only triggered with `run benchmark` label.

conditionally trigger benchmarkCI

---

.gitignore
.travis.yml
docs/Project.toml
docs/demos/config.json
docs/demos/filters/median_filter.jl
docs/make.jl

The purpose here is to provide an example to work on the remote page feature in DemoCards. (https://github.com/johnnychen94/DemoCards.jl/issues/72)
Adds a `median_filter.jl` example to explain how `mapwindow` is used in practice. (I think it answers the question in https://github.com/JuliaImages/ImageFiltering.jl/pull/14#issuecomment-694343995)

add a demo for median filters

---

precompile/script.jl
src/ImageFiltering.jl
src/border.jl
src/kernel.jl
src/kernelfactors.jl
src/mapwindow.jl
src/precompile.jl

On the current release, the first call looks like this:
```julia
julia> @time imfilter(img, KernelFactors.gaussian((3,3)));
2.135609 seconds (3.46 M allocations: 211.109 MiB, 12.01% gc time, 94.98% compilation time)
julia> @time mapwindow(extrema, img, (3,3))
0.756083 seconds (1.17 M allocations: 68.258 MiB, 6.57% gc time, 99.89% compilation time)
```
On this branch, it looks like this:
```julia
julia> @time imfilter(img, KernelFactors.gaussian((3,3)));
0.620004 seconds (362.78 k allocations: 40.455 MiB, 1.47% gc time, 96.09% compilation time)
julia> @time mapwindow(extrema, img, (3,3))
0.385470 seconds (334.52 k allocations: 19.585 MiB, 9.43% gc time, 99.82% compilation time)
```
Quite a nice reduction in latency.
I should note this requires …

Add some precompiles

---

docs/make.jl

It's not very helpful to push preview for every PR; it occupies a lot of storage and makes normal clones slower (unless the users explicitly clone one specific branch). For this reason, I've commented it out. Anyone with write-permission that wants a docs preview can temporarily remove the comment to enable it.

disable docs push preview

---

Project.toml
src/ImageFiltering.jl
src/compat.jl
src/extrema.jl
test/extrema.jl
test/runtests.jl

I think (?) the best way to do this is to make a minor bump. So we should make sure we move everything at once. Am I missing things? What about `imROF`?
xref https://github.com/JuliaImages/ImageSegmentation.jl/pull/72

Move extremization, blob_LoG from Images

---

src/kernel.jl
src/kernelfactors.jl
test/specialty.jl

These come from Images.jl and are part of moving most/all code
out to make it a meta-package.
As annotated in https://github.com/JuliaImages/Images.jl/pull/971, these may be the last of the moves here (`gaussian_pyramid` does not seem likely to move). Consequently, once this merges we could release a new version, unblocking https://github.com/JuliaImages/ImageSegmentation.jl/pull/72, or we could wait for #214 and/or #225.

Add `box` and `laplacian2d`

---

src/imfilter.jl

Several intermediate steps in `filtfft` are allocating when they don't need to be.
Results of this change on one of my operations:
Before: 86.106 ms (200 allocations: 140.55 MiB)
After: 72.876 ms (196 allocations: 113.27 MiB)
19% improvement in time, 24% improvement in allocation size.

Reduce unnecessary allocations in `filtfft`

---

.gitignore
Project.toml
benchmark/benchmarks.jl
docs/src/function_reference.md
src/ImageFiltering.jl
src/models.jl
test/cuda/Project.toml
test/cuda/models.jl
test/cuda/runtests.jl
test/models.jl
test/runtests.jl

Moved from https://github.com/JuliaImages/ImageBase.jl/pull/24
The test codes for CUDA are maintained in an independent folder `test/cuda` with its own set of `Project.toml`. We don't have CI setup so I manually test it in my local machine. My plan is to set up GPU CI in Images.jl only after we finish https://github.com/JuliaImages/Images.jl/issues/898, and use a script to collect all distributed CUDA-only tests in all packages.
```julia
(ImageFiltering) pkg> activate test/cuda
julia> include("test/cuda/runtests.jl")
Test Summary:  | Pass  Total
ImageFiltering |   28     28
```
TODO:

implement generic ROF model using Chambolle04 primal-dual method

---

src/imfilter.jl

Putting the string interpolation behind a `@noinline` is the key change,
but it doesn't hurt to hoist the range creation.
Of the few remaining allocations, about half will be fixed by
https://github.com/JuliaLang/julia/pull/43990, as they are another
instance of https://github.com/JuliaLang/julia/issues/35972

Less alloc in TriggsSdika filtering (fix #243)

---

src/imfilter.jl

The docstrings are not consistent with the tutorials (`FFT()` rather than `Algorithm.FFT()`).

[docs] imfilter

---

src/imfilter.jl

Fixes https://github.com/JuliaImages/ImageFiltering.jl/issues/265
This is a naive swap out. There may be refactoring that should happen at a higher level with the buffer management.
Untested locally.

replace bad threadid buffering

---

src/imfilter.jl
test/2d.jl

When using the FFT algorithm, previously there was only a method that
used the `rfft` and `irfft` methods which rely on getting a Real array
input. Added a method and specialization that uses the the old method
for Real valued arrays and a new method that calls `fft` and `ifft` for
other arrays.

feat: Allow Complex valued FFT

---

src/ImageFiltering.jl

Not sure if this is the right way to fix this - the warning goes away but lots of test failures in 1.12. I think this PR should be ok to merge so long as it passes on 1.11.
1.12 test failures will need separate investigation, which is not related to this PR.

Fix warnings for Julia 1.12

---

docs/demos/search/template_matching.jl

The indexing of the result of `component_centroids` in the docs was wrong, because it is zero-indexed, not one-indexed. Using `begin+1` instead of 2 is better and clearer.

Update template_matching.jl in docs

---

Project.toml
src/border.jl

`padindex` results in a large number of allocations due to multiple array creations and concatenations. This PR only creates a single array and values are copied into it.

Cut allocations in `padindex`
