- REQUIRE
- src/ImagesFiltering.jl
- src/kernel.jl
- test/runtests.jl
This is the foundation for Gaussian filtering, but implemented in a much more flexible way than in "old" Images.jl.
> Implment IIR filtering (Triggs-Sdika)

- src/imfilter.jl
- src/utils.jl
- test/nd.jl
- test/runtests.jl
Ref #17. This is basically a redo of #20.
> Detect overflow, but don't widen by default

- .travis.yml
- src/border.jl
- test/border.jl
- test/gradient.jl
- test/runtests.jl
The fact that this is possible is thanks to the new StaticArrays.
> Fix remaining errors on Julia 0.6

- test/border.jl
julia PR 18457, merge commit 35b3470eb67f492d26c8ab9fa9e0af0c7c22a6ea
> more specific version cutoff for type system rewrite

- README.md
> Add links to related packages

- src/kernelfactors.jl
- test/specialty.jl
> Fix KernelFactors.gaussian for sigma = 0

- .travis.yml
- REQUIRE
- appveyor.yml
- src/ImageFiltering.jl
- src/imfilter.jl
- src/kernel.jl
- src/mapwindow.jl
- test/2d.jl
- test/border.jl
- test/gabor.jl
- test/gradient.jl
- test/mapwindow.jl
- test/specialty.jl
This set of changes makes more tests work, gets some common filtering calls from other packages working, and obviates the deprecations observed by me so far.  The "tests work" part depends on some pending PRs to TiledIterations.
> A few more patches for v0.7

- .travis.yml
- test/specialty.jl
Punt on a strange test failure discovered by Travis.
> Minor adjustments for 0.7

- src/kernel.jl
> Add closing parens in docstring (fixes #62)

- src/mapwindow.jl
- test/mapwindow.jl
Thanks @jw3126  for the suggestion
> fixed issue #105 dimension deprecation

- Project.toml
> Add Random to extras in Project.toml

- src/imfilter.jl
- test/nd.jl
> Only use FFT algorithm for Numbers or Colorants

- src/mapwindow.jl
Only adds a few lines to the documentation of mapwindow.
> Add a few lines to documentation of mapwindow

- src/borderarray.jl
- test/border.jl
> fix similar() and axes() for BorderArray

- src/imfilter.jl
Fix https://github.com/JuliaImages/ImageFiltering.jl/issues/84
> Swap symmetric and reflect in doc

- src/kernel.jl
- test/specialty.jl
Fixing Moffat tests as noted by @timholy in https://github.com/JuliaImages/ImageFiltering.jl/pull/147#discussion_r387512964 and https://github.com/JuliaImages/ImageFiltering.jl/pull/147#discussion_r387521100
> Fix Moffat tests

- src/imfilter.jl
- test/2d.jl
> give friendly error message for Pad + indices case

- src/imfilter.jl
- test/2d.jl
- test/basic.jl
This PR consists of two independent commits.
closes #182
> update test case and fix test in multithreads environment

- .gitignore
- docs/demos/filters/min_max_filter.jl
#189 Added demo for max, min filters
> Add max min filter demo

- src/borderarray.jl
This partially revert commits 0ae368d27b7905773aa114d43d417c1fabe0b9b6
@timholy we need to merge this before we tag a release
> partially revert "Fix some ambiguities on nightly (#191)"

- src/specialty.jl
> Fix sign in imgradients

- src/imfilter.jl
- test/nd.jl
Fixes `imfilter`ing vectors with ±Inf
> Don't use FFT with non-finite input

- docs/demos/config.json
- docs/make.jl
I have no idea if this works on CI environments so let's try and see.
> Fix Plots segfaults when generating demos

- test/2d.jl
> fixup: add missing imports

- Project.toml
Looks like your compathelper is not running so this is just a manual PR, haven't checked tests
> Support DataStructures v0.19, bump patch version
